default:
  port: 2000
  ssl: false
  confirm: key
  temp: /tmp
  mongo: mongodb://127.0.0.1:27017/testclan
  key:
    paypal:
      key: YourKeyDev
      secret: YourSecretDev
    coinbase:
      key: YourKeyDev
      secret: YourSecretDev
    facebook:
      key: YourKeyDev
      secret: YourSecretDev
  app:
    api: /api
    cdn: /cdn

production:
  ssl: true
  mongo:
      protocol: mongodb
      slashes: true
      hostname: #{process.env.OPENSHIFT_MONGODB_DB_HOST}
      port: #{process.env.OPENSHIFT_MONGODB_DB_PORT}
      pathname: #{process.env.OPENSHIFT_APP_NAME}
      pass: #{process.env.OPENSHIFT_MONGODB_DB_USERNAME}
      user: #{process.env.OPENSHIFT_MONGODB_DB_PASSWORD}
  confirm: #{process.env.OPENSHIFT_APP_UUID}
  temp: #{process.env.OPENSHIFT_TMP_DIR}
  key:
    paypal:
      key: #{process.env.PAYPAL_KEY}
      secret: #{process.env.PAYPAL_SECRET}
  port: #{process.env.OPENSHIFT_NODEJS_PORT}
  ip: #{process.env.OPENSHIFT_NODEJS_IP}